#!/bin/bash
Rscript -e "options("dsc_download"=T, "dpd_download"=T); rmarkdown::render('dashboard.Rmd', quiet=T)"
rsync -a dashboard.html \
    pipitone.ca:websites/projects.jon.pipitone.ca/drug-shortages/index.html
